# Generated by Django 5.1.5 on 2025-02-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='cefr',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='cefr',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='cefr',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='cefrresult',
            name='cefr',
        ),
        migrations.RemoveField(
            model_name='cefrresult',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dtmresult',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dtmresult',
            name='dtm',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='block',
            name='questions',
        ),
        migrations.AddField(
            model_name='block',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dtm_questions', to='users.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DTMQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer_a', models.CharField(max_length=1000)),
                ('answer_b', models.CharField(max_length=1000)),
                ('answer_c', models.CharField(max_length=1000)),
                ('answer_d', models.CharField(max_length=1000)),
                ('correct_answer', models.CharField(max_length=1000)),
                ('point', models.DecimalField(decimal_places=2, max_digits=5)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.block')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CEFR',
        ),
        migrations.DeleteModel(
            name='CEFRResult',
        ),
        migrations.DeleteModel(
            name='DTMResult',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
