# Generated by Django 5.1.5 on 2025-02-11 06:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_question_answers_remove_cefr_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtmquestion',
            options={'verbose_name': 'DTM Savol', 'verbose_name_plural': 'DTM Savollar'},
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_a',
            field=ckeditor.fields.RichTextField(verbose_name='A Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_b',
            field=ckeditor.fields.RichTextField(verbose_name='B Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_c',
            field=ckeditor.fields.RichTextField(verbose_name='C Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_d',
            field=ckeditor.fields.RichTextField(verbose_name='D Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='correct_answer',
            field=models.CharField(choices=[('a', 'A Variant'), ('b', 'B Variant'), ('c', 'C Variant'), ('d', 'D Variant')], max_length=1000, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='question',
            field=ckeditor.fields.RichTextField(verbose_name='Savol'),
        ),
    ]
