# Generated by Django 5.1.5 on 2025-02-11 06:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_dtmquestion_options_alter_dtmquestion_answer_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_a',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='A Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_b',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='B Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_c',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='C Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='answer_d',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='D Variant'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Savol'),
        ),
    ]
