# Generated by Django 5.1.5 on 2025-02-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_dtmquestion_answer_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='dtm',
            name='block_1',
        ),
        migrations.RemoveField(
            model_name='dtm',
            name='block_3',
        ),
        migrations.RemoveField(
            model_name='dtm',
            name='block_5',
        ),
        migrations.RemoveField(
            model_name='dtm',
            name='block_2',
        ),
        migrations.RemoveField(
            model_name='dtm',
            name='block_4',
        ),
        migrations.RemoveField(
            model_name='dtmquestion',
            name='block',
        ),
        migrations.RemoveField(
            model_name='dtm',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='DTMQuestion',
        ),
        migrations.DeleteModel(
            name='DTM',
        ),
    ]
