# Generated by Django 5.1.5 on 2025-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_student_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=1000, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=1000, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=1000, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=1000, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rural',
            field=models.CharField(max_length=1000, verbose_name='Qishloq'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=1000, verbose_name='Maktab nomi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(max_length=1000, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Foydalanuvchi nomi'),
        ),
    ]
