# Generated by Django 5.1.5 on 2025-02-11 10:07

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='cefr',
            options={'verbose_name': 'CEFR', 'verbose_name_plural': 'CEFR'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='cefr.question', verbose_name='Savol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value_1',
            field=models.CharField(max_length=255, verbose_name='1-qiymat'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value_2',
            field=models.CharField(max_length=255, verbose_name='2-qiymat'),
        ),
        migrations.AlterField(
            model_name='cefr',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='cefr',
            name='name',
            field=models.CharField(max_length=255, verbose_name='CEFR nomi'),
        ),
        migrations.AlterField(
            model_name='cefr',
            name='participants',
            field=models.ManyToManyField(related_name='cefr_participants', to=settings.AUTH_USER_MODEL, verbose_name='Qatnashchilar'),
        ),
        migrations.AlterField(
            model_name='cefr',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cefr_subject', to='cefr.subject', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='question',
            name='cefr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cefr_questions', to='cefr.cefr', verbose_name='CEFR'),
        ),
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Fan nomi'),
        ),
    ]
