# Generated by Django 5.1.5 on 2025-02-11 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0002_alter_answer_options_alter_cefr_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='point',
        ),
        migrations.AlterField(
            model_name='answer',
            name='value_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2-qiymat'),
        ),
        migrations.AlterField(
            model_name='cefr',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='cefr_participants', to=settings.AUTH_USER_MODEL, verbose_name='Qatnashchilar'),
        ),
    ]
