# Generated by Django 5.1.5 on 2025-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cefr', '0003_remove_question_point_alter_answer_value_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefr',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Narx'),
            preserve_default=False,
        ),
    ]
