# Generated by Django 5.1.5 on 2025-02-11 06:47

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('block_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_1', to='dtm.block')),
                ('block_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_2', to='dtm.block')),
                ('block_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_3', to='dtm.block')),
                ('block_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_4', to='dtm.block')),
                ('block_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_5', to='dtm.block')),
                ('participants', models.ManyToManyField(blank=True, related_name='dtm_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DTMQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Savol')),
                ('answer_a', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='A Variant')),
                ('answer_b', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='B Variant')),
                ('answer_c', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='C Variant')),
                ('answer_d', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='D Variant')),
                ('correct_answer', models.CharField(choices=[('a', 'A Variant'), ('b', 'B Variant'), ('c', 'C Variant'), ('d', 'D Variant')], max_length=1000, verbose_name="To'g'ri javob")),
                ('point', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ball')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dtm.block')),
            ],
            options={
                'verbose_name': 'DTM Savol',
                'verbose_name_plural': 'DTM Savollar',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_questions', to='dtm.subject'),
        ),
    ]
