# Generated by Django 5.1.5 on 2025-02-11 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Fan bloklar', 'verbose_name_plural': 'Fan bloklar'},
        ),
        migrations.AlterModelOptions(
            name='dtm',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='dtmquestion',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fanlar', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AddField(
            model_name='dtm',
            name='duration',
            field=models.IntegerField(default=90, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Fan blok nomi'),
        ),
        migrations.AlterField(
            model_name='block',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_questions', to='dtm.subject', verbose_name='Fan'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='block_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_1', to='dtm.block', verbose_name='Fan blok 1'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='block_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_2', to='dtm.block', verbose_name='Fan blok 2'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='block_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_3', to='dtm.block', verbose_name='Fan blok 3'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='block_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_4', to='dtm.block', verbose_name='Fan blok 4'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='block_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_block_5', to='dtm.block', verbose_name='Fan blok 5'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Test nomi'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='dtm_participants', to=settings.AUTH_USER_MODEL, verbose_name='Qatnashchilar'),
        ),
        migrations.AlterField(
            model_name='dtmquestion',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dtm.block', verbose_name='Fan blok'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Fan nomi'),
        ),
    ]
