# Generated by Django 5.1.5 on 2025-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtm', '0002_alter_block_options_alter_dtm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtm',
            name='duration',
            field=models.IntegerField(default=90, verbose_name='Vaqt (minut)'),
        ),
    ]
