# Generated by Django 5.1.5 on 2025-02-11 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtm', '0003_alter_dtm_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dtm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DTMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ball')),
                ('cases', models.JSONField(default=dict, verbose_name='Javoblar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('dtm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dtm.dtm', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtm_results', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
