# Generated by Django 5.1.5 on 2025-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtm', '0004_dtm_created_dtmresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtm',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narxi'),
        ),
    ]
